# - - - - - - - - - - - - - - - #
#       GLOBAL SETTINGS         #
# - - - - - - - - - - - - - - - #

# Color for OP players. For example, b = §b
op-nickname-color: "4"

# Chat formatting settings
chat-formatting:

  # Available methods:
  # 1 - default, local/global
  # 2 - single format (local or global, with placeholders)
  # 3 - default Minecraft format (with placeholders)
  format-method: 1

  # local or global, used in format-method 2
  single-chat-type: "global"

  # blocks, used in format-method 1
  local-chat-radius: 100 # blocks, used in format-method 1

  # Local chat settings
  # Used in format-method 1 or 2 (if single-chat-type is local)
  # If you use ClanSystem plugin - you can use placeholder %clantag% to display clan tag.
  local-chat-format: "§7[§aL§7] §r{prefix}§r {player}{suffix}§r §a» §8{msg}" # used in format-method 1 or 2

  # Global chat settings
  # Used in format-method 1 or 2 (if single-chat-type is global)
  # Enter this symbol before a message to write a message to the global chat.
  global-chat-symbol: "!"

  # Formatting
  # Used in format-method 1 or 2 (if single-chat-type is global)
  global-chat-format: "§7[§4G§7] §r{prefix}§r {player}{suffix}§r §a» §f{msg}"

  # Default minecraft format
  # used in format-method 3
  default-chat-format: "§r<{prefix}§r{player}{suffix}§r> §f{msg}"

# Do not touch this option :)
debug: false

# Prefix in settings [ESC] and in display name
prefix-in-settings-and-head:
  enabled: false
  format: "[{prefix}] {player}{suffix}"

# - - - - - - - - - - - - - - - #
#       /prefix command         #
# - - - - - - - - - - - - - - - #

# maximum prefix charters in prefix
prefix-max-characters: 15

# minimum charters in prefix
prefix-min-characters: 3

# Enabled charters in prefix
allowed-characters: "A-Za-z0-9_-"

# Banned prefixes
prefixes-blacklist:
  - admin
  - creator
  - owner
  - moderator
  - administrator

# - - - - - - - - - - - - - - - #
#        /nick command          #
# - - - - - - - - - - - - - - - #

max-nick-characters-length: 15 # Maximum characters allowed in a nickname
min-nick-characters-length: 3 # Minimum characters required in a nickname
allowed-characters-in-nick: "A-Za-z0-9_-" # Allowed characters in nicknames
allow-colored-nick: false # Allow using color codes in nicknames (e.g., &b)
fake-nickname-character: "italic" # You also can use 'italic' or 'bold'
allow-duplicate-nicknames: false # Allow a player to set fake nicknames that are already used by another player
# Banned nicknames
nicknames-blacklist:
  - admin
  - creator
  - owner
  - moderator
  - administrator

# - - - - - - - - - - - - - - - #
#        CHAT FILTERING         #
# - - - - - - - - - - - - - - - #

chat-filtering:
  enabled: true
  cooldown-for-messages: 3 # seconds
  max-message-characters: 200
  max-messages-repetition: 5
  # Available methods: Kick, Message, Command
  repetition-punishment: "Message"
  # Used only if repetition-punishment is Command
  # {player} - player's name
  punishment-command: 'mute 30 minutes "{player}" Too many repeat'
