# - - - - - - - - - - - - - - - #
#       GLOBAL SETTINGS         #
# - - - - - - - - - - - - - - - #

# Color for OP players. For example, b = §b
op-nickname-color: "4"

# Chat formatting settings
chat-formatting:

  # Available methods:
  # 1 - default, local/global
  # 2 - single format (local or global, with placeholders)
  # 3 - default Minecraft format (with placeholders)
  format-method: 1

  # local or global, used in format-method 2
  single-chat-type: "global"

  # blocks, used in format-method 1
  local-chat-radius: 100 # blocks, used in format-method 1

  # Local chat settings
  # Used in format-method 1 or 2 (if single-chat-type is local)
  # If you use ClanSystem plugin - you can use placeholder %clantag% to display clan tag.
  local-chat-format: "§7[§aL§7] §r{prefix}§r {player}{suffix}§r §a» §8{msg}" # used in format-method 1 or 2

  # Global chat settings
  # Used in format-method 1 or 2 (if single-chat-type is global)
  # Enter this symbol before a message to write a message to the global chat.
  global-chat-symbol: "!"

  # Formatting
  # Used in format-method 1 or 2 (if single-chat-type is global)
  global-chat-format: "§7[§4G§7] §r{prefix}§r {player}{suffix}§r §a» §f{msg}"

  # Default minecraft format
  # used in format-method 3
  default-chat-format: "§r<{prefix}§r{player}{suffix}§r> §f{msg}"

# Do not touch this option :)
debug: false

# Prefix in settings [ESC] and in display name
prefix-in-settings-and-head:
  enabled: false
  format: "[{prefix}] {player}{suffix}"

# - - - - - - - - - - - - - - - #
#       /prefix command         #
# - - - - - - - - - - - - - - - #

prefix:
  # maximum prefix charters in prefix
  max-characters-in-prefix: 15

  # minimum charters in prefix
  min-characters-in-prefix: 3

  # Enabled charters in prefix
  allowed-characters: "A-Za-z0-9_-"

  # Banned prefixes
  prefixes-blacklist:
    - admin
    - creator
    - owner
    - moderator
    - administrator

# - - - - - - - - - - - - - - - #
#        /nick command          #
# - - - - - - - - - - - - - - - #

nick:
  # Maximum characters allowed in a nickname
  max-characters-length: 15

  # Minimum characters required in a nickname
  min-characters-length: 3

  # Allowed characters in nicknames
  allowed-characters-in-nick: "A-Za-z0-9_-"

  # Allow using color codes in nicknames (e.g., §b)
  allow-colored-nick: false

  # Character before fake nickname
  # You also can use 'italic', 'bold' and all characters
  fake-nickname-character: "italic"

  # Allow a player to set fake nicknames that are already used by another player
  allow-duplicate-nicknames: false

  # Banned nicknames
  nicknames-blacklist:
    - admin
    - creator
    - owner
    - moderator
    - administrator

# - - - - - - - - - - - - - - - #
#        CHAT FILTERING         #
# - - - - - - - - - - - - - - - #

chat-filtering:
  enabled: true
  cooldown-for-messages: 3 # seconds
  max-message-characters: 200
  max-messages-repetition: 5
  # Available methods: Kick, Message, Command
  repetition-punishment: "Message"
  # Used only if repetition-punishment is Command
  # {player} - player's name
  punishment-command: 'mute 30 minutes "{player}" Too many repeat'
