# - - - - - - - - - - - - - - - #
#       GLOBAL SETTINGS         #
# - - - - - - - - - - - - - - - #

# Providers: luckperms, multipass, fallback
provider: "luckperms"

# Color for OP players. For example, b = §b
op-nickname-color: "4"

# Local chat settings
# If you use ClanSystemMX plugin - you can use placeholder %clantag% to display clan tag.
local-chat-radius: 100 # blocks
local-chat-format: "§7[§aL§7] §7[{prefix}§r§7] §f{player}{suffix} §a» §8{msg}"

# Global chat settings
global-chat-symbol: "!" # Type ! before your message to write to global chat
global-chat-format: "§7[§4G§7] §7[{prefix}§r§7] §f{player}{suffix} §a» §f{msg}"

# Do not touch this option :)
debug: false

# Prefix in settings [ESC] and in display name
prefix-in-settings-and-head:
  enabled: true
  format: "[{prefix}] {player}{suffix}"

# - - - - - - - - - - - - - - - #
#       /prefix command         #
# - - - - - - - - - - - - - - - #

# maximum prefix charters in prefix
prefix-max-characters: 15

# minimum charters in prefix
prefix-min-characters: 3

# Enabled charters in prefix
allowed-characters: "A-Za-z0-9_-"

# Banned prefixes
prefixes-blacklist:
  - admin
  - creator
  - owner
  - moderator
  - administrator

# - - - - - - - - - - - - - - - #
#        /nick command          #
# - - - - - - - - - - - - - - - #

max-nick-characters-length: 15 # Maximum characters allowed in a nickname
min-nick-characters-length: 3 # Minimum characters required in a nickname
allowed-characters-in-nick: "A-Za-z0-9_-" # Allowed characters in nicknames
allow-colored-nick: false # Allow using color codes in nicknames (e.g., &b)
fake-nickname-character: "~" # You also can use ITALIC or BOLD
allow-duplicate-nicknames: false # Allow a player to set fake nicknames that are already used by another player
# Banned nicknames
nicknames-blacklist:
  - admin
  - creator
  - owner
  - moderator
  - administrator

# - - - - - - - - - - - - - - - #
#        CHAT FILTERING         #
# - - - - - - - - - - - - - - - #

chat-filtering:
  enabled: true
  cooldown-for-messages: 3 # seconds
  max-message-characters: 200
  max-messages-repetition: 5
  # Available methods: Kick, Message, Command
  repetition-punishment: "Message"
  # Used only if repetition-punishment is Command
  # {player} - player's name
  punishment-command: 'mute 30 minutes "{player}" Too many repeat'
