name: EssentialsChat
version: ${pom.version}
main: me.criex.essentialschat.EssentialsChat
api: ["1.1.0", "1.0.14"]
depend:
  - "PlaceholderAPI"
softdepend:
  - "LuckPerms"
  - "Multipass"
author: "Criex"
description: Chat plugin with global and local chat support for LuckPerms or Multipass
commands:
  prefix:
    permission: essentialschat.prefix.setprefix
    description: Change your prefix
  nick:
    permssion: essentialschat.nick.setnick
    description: Change your fake nick
  realname:
    permision: essentialschat.nick.realname
    description: Get player's real name
permissions:
  essentialschat.prefix.setprefix:
    default: op
  essentialschat.nick.setnick:
    default: op
  essentialschat.nick.realname:
    default: op
