name: EssentialsChat
version: ${version}
main: me.criex.essentialschat.EssentialsChat
api: ["1.1.0", "1.0.14"]
depend:
  - "PlaceholderAPI"
softdepend:
  - "LuckPerms"
  - "Multipass"
author: "Criex"
description: Chat plugin with global and local chat support for LuckPerms or Multipass
permissions:
  essentialschat.commands.prefix:
    default: op
  essentialschat.commands.nick:
    default: op
  essentialschat.commands.realname:
    default: op
