name: EssentialsChat
version: 1.0.2
main: ru.rexlite.EssentialsChat
api: ["3.0.0", "4.0.0", "5.0.0"]
softdepend: [LuckPerms, Multipass]
authors: ["Criex", "Rexl1te"]
description: Chat plugin with global and local chat support for LuckPerms or Multipass