name: EssentialsChat
version: 1.0.4
main: ru.rexlite.EssentialsChat
api: ["1.1.0"]
softdepend: [LuckPerms, Multipass]
author: ["Criex", "Rexl1te"]
description: Chat plugin with global and local chat support for LuckPerms or Multipass
